// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZBZ9qENBJO6rjLwSptRRtukDq4fnuThI',
    appId: '1:453684979443:web:05c5746e518a804f63b986',
    messagingSenderId: '453684979443',
    projectId: 'rakshakauth-2f32b',
    authDomain: 'rakshakauth-2f32b.firebaseapp.com',
    storageBucket: 'rakshakauth-2f32b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeLpas1ubAauaiJSvKOfSGNrjofLlnz6Q',
    appId: '1:453684979443:android:2e47c20534ee710963b986',
    messagingSenderId: '453684979443',
    projectId: 'rakshakauth-2f32b',
    storageBucket: 'rakshakauth-2f32b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSDWB11aPrvrW_JBChXWYfq6fqI7dnee4',
    appId: '1:453684979443:ios:fd323a28ac12897463b986',
    messagingSenderId: '453684979443',
    projectId: 'rakshakauth-2f32b',
    storageBucket: 'rakshakauth-2f32b.firebasestorage.app',
    iosClientId: '453684979443-fhghplm7r1feh1gt0s1k8823eke884pv.apps.googleusercontent.com',
    iosBundleId: 'com.example.temp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSDWB11aPrvrW_JBChXWYfq6fqI7dnee4',
    appId: '1:453684979443:ios:fd323a28ac12897463b986',
    messagingSenderId: '453684979443',
    projectId: 'rakshakauth-2f32b',
    storageBucket: 'rakshakauth-2f32b.firebasestorage.app',
    iosClientId: '453684979443-fhghplm7r1feh1gt0s1k8823eke884pv.apps.googleusercontent.com',
    iosBundleId: 'com.example.temp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZBZ9qENBJO6rjLwSptRRtukDq4fnuThI',
    appId: '1:453684979443:web:9823623b6c25d74c63b986',
    messagingSenderId: '453684979443',
    projectId: 'rakshakauth-2f32b',
    authDomain: 'rakshakauth-2f32b.firebaseapp.com',
    storageBucket: 'rakshakauth-2f32b.firebasestorage.app',
  );

}